### ISSUE TITLE
More specific calibration types

### ISSUE THREAD

**Issue by adamml** [nvs-vocabs/W03#1]
I was wondering if any consideration had been given to providing more explicit detail on the calibration type than is currently supported by [W030003](http://vocab.nerc.ac.uk/collection/W03/current/W030003/)?

Specifically, I was thinking:

- **Manufacturer's calibration** A calibration performed by the manufacturer of the device or system.
- **In-situ calibration** A calibration performed against discrete in-situ measurements, such as from water-bottle samples.
- **Accredited authority or laboratory calibration** A calibration performed by an accredited authority or laboratory, normally for compliance with national or international quality standards, procedures or guidelines.

Each of these could sit as child terms of W030003

**Comment by adamml** [comment]
Just bumping this issue...

**Comment by gwemon** [comment]
Our ref: BODCNVS-668

**Comment by louatbodc** [comment]
New concepts created:

W030015	Manufacturer's calibration
W030016	In-situ calibration
W030017	Accredited authority or laboratory calibration

Child relationships also created
